const TEAM_FLAGS: Record<string, string> = {
  // CONMEBOL
  'Argentina': 'ar',
  'Brazil': 'br',
  'Uruguay': 'uy',
  'Colombia': 'co',
  'Ecuador': 'ec',
  'Paraguay': 'py',
  'Peru': 'pe',
  'Bolivia': 'bo',
  'Venezuela': 've',
  'Chile': 'cl',

  // UEFA
  'France': 'fr',
  'Germany': 'de',
  'Spain': 'es',
  'Portugal': 'pt',
  'England': 'gb-eng',
  'Netherlands': 'nl',
  'Belgium': 'be',
  'Poland': 'pl',
  'Switzerland': 'ch',
  'Croatia': 'hr',
  'Serbia': 'rs',
  'Denmark': 'dk',
  'Austria': 'at',
  'Turkey': 'tr',
  'Ukraine': 'ua',
  'Slovakia': 'sk',
  'Czechia': 'cz',
  'Czech Republic': 'cz',
  'Romania': 'ro',
  'Hungary': 'hu',
  'Albania': 'al',
  'Slovenia': 'si',
  'Iceland': 'is',
  'Greece': 'gr',
  'Georgia': 'ge',
  'Scotland': 'gb-sct',
  'Wales': 'gb-wls',
  'Bosnia and Herzegovina': 'ba',
  'Bosnia-Herzegovina': 'ba',
  'North Macedonia': 'mk',
  'Montenegro': 'me',
  'Armenia': 'am',
  'Kosovo': 'xk',
  'Kazakhstan': 'kz',
  'Italy': 'it',
  'Sweden': 'se',
  'Norway': 'no',
  'Finland': 'fi',
  'Ireland': 'ie',
  'Bulgaria': 'bg',
  'Cyprus': 'cy',
  'Belarus': 'by',
  'Luxembourg': 'lu',
  'Lithuania': 'lt',
  'Latvia': 'lv',
  'Estonia': 'ee',
  'Moldova': 'md',

  // CONCACAF
  'United States': 'us',
  'USA': 'us',
  'Mexico': 'mx',
  'Canada': 'ca',
  'Honduras': 'hn',
  'Panama': 'pa',
  'Costa Rica': 'cr',
  'El Salvador': 'sv',
  'Jamaica': 'jm',
  'Guatemala': 'gt',
  'Suriname': 'sr',
  'Trinidad and Tobago': 'tt',
  'Cuba': 'cu',
  'Haiti': 'ht',
  'Nicaragua': 'ni',
  'Belize': 'bz',
  'Antigua and Barbuda': 'ag',
  'Barbados': 'bb',
  'Guyana': 'gy',
  'Curaçao': 'cw',

  // AFC
  'Japan': 'jp',
  'South Korea': 'kr',
  'Korea Republic': 'kr',
  'Australia': 'au',
  'Saudi Arabia': 'sa',
  'Iran': 'ir',
  'Iraq': 'iq',
  'Jordan': 'jo',
  'Indonesia': 'id',
  'China PR': 'cn',
  'China': 'cn',
  'Uzbekistan': 'uz',
  'Oman': 'om',
  'Bahrain': 'bh',
  'Qatar': 'qa',
  'UAE': 'ae',
  'United Arab Emirates': 'ae',
  'India': 'in',
  'Kyrgyzstan': 'kg',
  'Tajikistan': 'tj',
  'Syria': 'sy',
  'Palestine': 'ps',
  'Lebanon': 'lb',
  'Vietnam': 'vn',
  'Thailand': 'th',
  'Malaysia': 'my',
  'Philippines': 'ph',
  'Myanmar': 'mm',
  'Afghanistan': 'af',
  'Kuwait': 'kw',

  // CAF
  'Morocco': 'ma',
  'Egypt': 'eg',
  'Senegal': 'sn',
  'Nigeria': 'ng',
  "Ivory Coast": 'ci',
  "Côte d'Ivoire": 'ci',
  'Cameroon': 'cm',
  'Ghana': 'gh',
  'Algeria': 'dz',
  'Tunisia': 'tn',
  'South Africa': 'za',
  'Mali': 'ml',
  'Zambia': 'zm',
  'DR Congo': 'cd',
  'Congo DR': 'cd',
  'Democratic Republic of Congo': 'cd',
  'Equatorial Guinea': 'gq',
  'Cape Verde': 'cv',
  'Cape Verde Islands': 'cv',
  'Tanzania': 'tz',
  'Comoros': 'km',
  'Angola': 'ao',
  'Namibia': 'na',
  'Benin': 'bj',
  'Burkina Faso': 'bf',
  'Kenya': 'ke',
  'Uganda': 'ug',
  'Rwanda': 'rw',
  'Ethiopia': 'et',
  'Sudan': 'sd',
  'Libya': 'ly',
  'Gabon': 'ga',
  'Guinea': 'gn',
  'Guinea-Bissau': 'gw',
  'Mozambique': 'mz',
  'Zimbabwe': 'zw',
  'Mauritania': 'mr',
  'Niger': 'ne',
  'Sierra Leone': 'sl',
  'Togo': 'tg',

  // OFC
  'New Zealand': 'nz',
  'Fiji': 'fj',
  'Papua New Guinea': 'pg',
  'Tahiti': 'pf',
}

export function getFlagUrl(teamName: string): string | null {
  const code = TEAM_FLAGS[teamName]
  if (!code) return null
  return `https://flagcdn.com/24x18/${code}.png`
}

export function getFlagUrlLarge(teamName: string): string | null {
  const code = TEAM_FLAGS[teamName]
  if (!code) return null
  return `https://flagcdn.com/48x36/${code}.png`
}
